### ISSUE TITLE
V1.1 Update

### ISSUE THREAD

**Issue by jondoetech** [jondoetech/CatchingSouls#6]
- [x] Configure admin view to return all data to admins frontend view.
- [x] Configure option to export a copy of the db to S3 bucket and export a copy of the tables json files to both S3 bucket and frontend, but manually and automatically.
- [x] Add error page to redirect to correct location

**Comment by Jon204D** [comment]
All marks have been checked, including a temp way to backup the db to AWS S3 Bucket. Pushing new code soon and will begin new deployment.
