### ISSUE TITLE
V1.2 Update

### ISSUE THREAD

**Issue by jondoetech** [jondoetech/CatchingSouls#7]
Security:
- [ ] Tighten security with token that is updated every minute if the user is still active, otherwise reassign new token on frontend and backend post validation for registered users.

DB related stuff:
- [x] Create a new admin page to view db related stuff like import and export.
- [x] Configure a way to run db import from AWS with a button.
- [x] Configure a notice on the frontend to show when db backup/import was successful.

Trivia related stuff:
- [x] Provide scripture evidence

Send us your trivia question page:
- [x] Create a form to allow users to send in their trivia question.

**Comment by Jon204D** [comment]
Cookies management is left to be updated...

**Comment by Jon204D** [comment]
Closing out since backend is being deployed...
