### ISSUE TITLE
V1.3

### ISSUE THREAD

**Issue by jondoetech** [jondoetech/CatchingSouls#8]
Security:
- [x] Tighten security with a token updated every minute if the user is still active; otherwise, reassign a new token on the frontend and backend post validation for registered users.

Styling:
- [x]  Update Colors for styling, for example, the "End Game" button in trivia, any cancel buttons, and so forth...
- [x] Reset fields button press to return to normal after an error... I.E. Login button...
- [x] Add more info to profile, like overall score...

Addition:
- [x] Add correct answer place holder for incorrect answer and verse.
- [x] Allow users to place in the church they attend...

Preferences:
- [x]  Find a way to store the last time the db was imported or exported and if it was successful...

**Comment by Jon204D** [comment]
All functionalities have been updated to be considered V1.3!
